# Generated by Django 2.0.6 on 2019-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0002_auto_20190625_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='inspection_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_3',
            field=models.BooleanField(default=False),
        ),
    ]
