# Generated by Django 2.0.6 on 2019-06-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0003_auto_20190625_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='check',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_base.AHU'),
        ),
    ]
