# Generated by Django 2.0.6 on 2019-06-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0004_auto_20190625_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahu',
            name='type',
        ),
    ]
