# Generated by Django 2.2.1 on 2019-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0006_ahu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahu',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
