# Generated by Django 2.0.6 on 2019-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0007_auto_20190625_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='slug',
            field=models.SlugField(default='a', max_length=250, unique_for_date='checked_date'),
        ),
    ]
