# Generated by Django 2.0.6 on 2019-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0008_check_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='slug',
        ),
        migrations.AlterField(
            model_name='check',
            name='serial_number',
            field=models.CharField(max_length=200, unique='serial_number'),
        ),
    ]
