# Generated by Django 2.0.6 on 2019-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0009_auto_20190630_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='serial_number',
            field=models.CharField(max_length=200),
        ),
    ]
