# Generated by Django 2.0.6 on 2019-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0010_auto_20190630_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_1', models.BooleanField(default=False)),
                ('inspection_2', models.BooleanField(default=False)),
                ('inspection_3', models.BooleanField(default=False)),
                ('inspection_4', models.BooleanField(default=False)),
                ('inspection_5', models.BooleanField(default=False)),
                ('inspection_6', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='inspection_1',
        ),
        migrations.RemoveField(
            model_name='check',
            name='inspection_2',
        ),
        migrations.RemoveField(
            model_name='check',
            name='inspection_3',
        ),
    ]
