# Generated by Django 2.0.6 on 2019-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0011_auto_20190702_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amber',
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='inspection_6',
            field=models.BooleanField(default=False),
        ),
    ]
