# Generated by Django 2.0.6 on 2019-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_base', '0014_auto_20190702_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='amber',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
