# Generated by Django 2.0.6 on 2019-07-02 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality_base', '0015_amber_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200)),
                ('inspection_1', models.BooleanField(default=False)),
                ('inspection_2', models.BooleanField(default=False)),
                ('inspection_3', models.BooleanField(default=False)),
                ('inspection_4', models.BooleanField(default=False)),
                ('inspection_5', models.BooleanField(default=False)),
                ('inspection_6', models.BooleanField(default=False)),
                ('comments', models.TextField(default='')),
                ('checked_date', models.DateTimeField(blank=True, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
